apiVersion: v1
kind: Service
metadata:
  name: model-serving-k8s-service
spec:
  type: NodePort
  selector:
    app: model-serving-k8s
  ports:
  - port: 8081
    targetPort: 8081
    nodePort: 30007
